"""Constants for the Femmto Scale integration."""

DOMAIN = "femmto_scale"
DEFAULT_NAME = "Femmto BWS12"

SERVICE_UUID = "0000ffb0-0000-1000-8000-00805f9b34fb"
NOTIFY_UUID = "0000ffb2-0000-1000-8000-00805f9b34fb"
WRITE_UUID = "0000ffb1-0000-1000-8000-00805f9b34fb"

WEIGHT_OFFSET = 0x680000

CONF_ADDRESS = "address"
CONF_NAME = "name"
CONF_MIN_WEIGHT_KG = "min_weight_kg"
CONF_RESET_WEIGHT_KG = "reset_weight_kg"
CONF_STABILITY_WINDOW_SECONDS = "stability_window_seconds"
CONF_STABILITY_DELTA_KG = "stability_delta_kg"
CONF_STABILITY_SAMPLES = "stability_samples"
CONF_LISTEN_DURATION_SECONDS = "listen_duration_seconds"
CONF_PERIODIC_RETRY_SECONDS = "periodic_retry_seconds"
CONF_CONNECT_COOLDOWN_SECONDS = "connect_cooldown_seconds"
CONF_REPEAT_STABLE_SAMPLES = "repeat_stable_samples"
CONF_STABLE_HOLD_SECONDS = "stable_hold_seconds"

DEFAULT_MIN_WEIGHT_KG = 5.0
DEFAULT_RESET_WEIGHT_KG = 2.0
DEFAULT_STABILITY_WINDOW_SECONDS = 2.5
DEFAULT_STABILITY_DELTA_KG = 0.10
DEFAULT_STABILITY_SAMPLES = 8
DEFAULT_LISTEN_DURATION_SECONDS = 90.0
DEFAULT_PERIODIC_RETRY_SECONDS = 10.0
DEFAULT_CONNECT_COOLDOWN_SECONDS = 1.0
DEFAULT_REPEAT_STABLE_SAMPLES = 5
DEFAULT_STABLE_HOLD_SECONDS = 10.0
